name: 'Set Persistent storages env variables'
description: 'Set the necessary '
inputs:
  bucket:            {default: 'arcticdb-ci-test-bucket-01', type: string, description: The name of the S3 bucket that we will test against}
  endpoint:          {default: 's3.eu-west-2.amazonaws.com', type: string, description: The address of the S3 endpoint}
  region:            {default: 'eu-west-2', type: string, description: The S3 region of the bucket}
  clear:             {default: 0, type: number, description: Controls whether we will clear the libraries in the versions stores that we test against}      
  aws_access_key:    {required: true, type: string, description: The value for the AWS Access key}      
  aws_secret_key:    {required: true, type: string, description: The value for the AWS Secret key}      
runs:
  using: "composite"
  steps:
    - name: Set real storage variables
      shell: bash
      
      run: |
        # Common
        echo "ARCTICDB_PERSISTENT_STORAGE_TESTS=1" >> $GITHUB_ENV
        echo "ARCTICDB_PERSISTENT_STORAGE_BRANCH_NAME=${{ github.run_id }}" >> $GITHUB_ENV
        # S3 Specific
        echo "ARCTICDB_REAL_S3_BUCKET=${{ inputs.bucket }}" >> $GITHUB_ENV
        echo "ARCTICDB_REAL_S3_ENDPOINT=${{ inputs.endpoint }}" >> $GITHUB_ENV
        echo "ARCTICDB_REAL_S3_REGION=${{ inputs.region }}" >> $GITHUB_ENV
        echo "ARCTICDB_REAL_S3_CLEAR=${{ inputs.clear }}" >> $GITHUB_ENV
        echo "ARCTICDB_REAL_S3_ACCESS_KEY=${{ inputs.aws_access_key }}" >> $GITHUB_ENV
        echo "ARCTICDB_REAL_S3_SECRET_KEY=${{ inputs.aws_secret_key }}" >> $GITHUB_ENV
