#!/usr/bin/env python3
"""
Create or update GitHub issues for CI failures and write a Slack summary.

Usage:
    track_ci_issues.py --input-dir <DIR> --run-id <RUN_ID> --run-url <URL> \
                       --repo <OWNER/REPO> --commit-sha <SHA> --output-file <FILE>

Inputs (read from --input-dir):
    failing_tests.txt  - One failing test per line
    failed_steps.txt   - One "job / step" entry per line

Output (written to --output-file):
    Slack summary lines (one per tracked item)

Requirements: gh (GitHub CLI)
"""
import argparse
import json
import subprocess
from datetime import datetime, timezone

GROUPING_THRESHOLD = 10


def run_gh(*args: str, check: bool = True) -> str:
    """Run a gh CLI command and return stdout."""
    result = subprocess.run(
        ["gh", *args],
        capture_output=True,
        text=True,
        check=check,
    )
    return result.stdout.strip()


def read_lines(path: str) -> list[str]:
    """Read non-empty lines from a file."""
    try:
        with open(path) as f:
            return [line.strip() for line in f if line.strip()]
    except FileNotFoundError:
        return []


def find_existing_issue(repo: str, label: str, title: str) -> int | None:
    """Search for an open issue with an exact title match. Returns issue number or None."""
    raw = run_gh(
        "issue", "list",
        "--repo", repo,
        "--label", label,
        "--state", "open",
        "--search", f'"{title}" in:title',
        "--json", "number,title",
    )
    if not raw:
        return None
    for issue in json.loads(raw):
        if issue["title"] == title:
            return issue["number"]
    return None


def get_issue_url(repo: str, number: int) -> str:
    raw = run_gh(
        "issue", "view", str(number),
        "--repo", repo,
        "--json", "url",
        "--jq", ".url",
    )
    return raw


def create_issue(repo: str, title: str, labels: list[str], body: str) -> str:
    """Create a GitHub issue. Returns the issue URL."""
    cmd = ["issue", "create", "--repo", repo, "--title", title, "--body", body]
    for label in labels:
        cmd.extend(["--label", label])
    return run_gh(*cmd)


def comment_on_issue(repo: str, number: int, body: str) -> None:
    run_gh("issue", "comment", str(number), "--repo", repo, "--body", body)


class IssueTracker:
    """Tracks CI failures as GitHub issues and accumulates a Slack summary."""

    def __init__(self, repo: str, run_id: str, run_url: str, commit_sha: str):
        self.repo = repo
        self.run_id = run_id
        self.run_url = run_url
        self.short_sha = commit_sha[:10]
        self.run_date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        self.slack_lines: list[str] = []

    def _failure_comment(self) -> str:
        return (
            f"### Another failure observed\n\n"
            f"- **Run:** {self.run_url}\n"
            f"- **Commit:** `{self.short_sha}`\n"
            f"- **Date:** {self.run_date}"
        )

    def _issue_footer(self) -> str:
        return (
            "---\n"
            "*This issue was automatically created by the flaky test tracker workflow.*\n"
            "*Add further failure occurrences as comments below.*"
        )

    def _failure_table(self) -> str:
        return (
            "### Failure history\n\n"
            "| Date | Run | Commit |\n"
            "|------|-----|--------|\n"
            f"| {self.run_date} | [Run #{self.run_id}]({self.run_url}) | `{self.short_sha}` |"
        )

    def track_item(self, name: str, title_prefix: str, label: str, body: str) -> None:
        """Find or create an issue for a single failure item."""
        issue_title = f"{title_prefix}: {name}"
        existing = find_existing_issue(self.repo, label, issue_title)

        if existing:
            print(f"  Found existing issue #{existing} - adding comment")
            comment_on_issue(self.repo, existing, self._failure_comment())
            url = get_issue_url(self.repo, existing)
            self.slack_lines.append(
                f":warning: *Known* — `{name}` (<{url}|#{existing}>)"
            )
        else:
            print(f"  No existing issue - creating new one")
            url = create_issue(
                self.repo, issue_title, [label, "autogenerated"], body
            )
            self.slack_lines.append(
                f":rotating_light: *New* — `{name}` (<{url}|issue>)"
            )

    def test_issue_body(self, test_name: str) -> str:
        return (
            f"## Flaky test failure\n\n"
            f"**Test:** `{test_name}`\n\n"
            f"This test has been detected as failing in CI.\n\n"
            f"{self._failure_table()}\n\n"
            f"{self._issue_footer()}"
        )

    def step_issue_body(self, step_entry: str) -> str:
        return (
            f"## Intermittent CI step failure\n\n"
            f"**Step:** `{step_entry}`\n\n"
            f"This CI step has failed. This is typically caused by transient "
            f"infrastructure issues (network timeouts, package mirrors, etc.).\n\n"
            f"{self._failure_table()}\n\n"
            f"{self._issue_footer()}"
        )

    def create_grouped_issue(self, item_type: str, items: list[str]) -> None:
        """Create a single issue listing all failures."""
        count = len(items)
        item_list = "\n".join(f"- `{item}`" for item in items)

        if item_type == "test":
            label = "flaky-test"
            heading = f"Grouped CI test failures ({count} tests)"
            description = (
                "Multiple tests failed in a single run, suggesting a common "
                "root cause rather than individual flaky tests."
            )
            slack_msg = f":rotating_light: *{count} tests failed* — likely correlated"
        else:
            label = "flaky-step"
            heading = f"Grouped CI step failures ({count} steps)"
            description = (
                "Multiple steps failed in a single run, suggesting a "
                "widespread infrastructure issue."
            )
            slack_msg = f":warning: *{count} steps failed* — likely infrastructure issue"

        body = (
            f"## {heading}\n\n"
            f"{description}\n\n"
            f"### Failures\n\n"
            f"{item_list}\n\n"
            f"- **Run:** [Run #{self.run_id}]({self.run_url})\n"
            f"- **Commit:** `{self.short_sha}`\n"
            f"- **Date:** {self.run_date}\n\n"
            f"---\n"
            f"*This issue was automatically created by the flaky test tracker workflow.*"
        )

        issue_title = f"{heading}: run #{self.run_id}"
        url = create_issue(self.repo, issue_title, [label, "autogenerated"], body)
        self.slack_lines.append(f"{slack_msg} (<{url}|issue>)")

    def handle_unparseable(self) -> None:
        """Handle failures where no specific test/step could be identified."""
        issue_title = "CI failures (unparseable)"
        existing = find_existing_issue(self.repo, "ci-failure", issue_title)

        if existing:
            print(f"Adding comment to existing unparseable issue #{existing}")
            comment = (
                f"### Another unparseable failure\n\n"
                f"- **Run:** {self.run_url}\n"
                f"- **Commit:** `{self.short_sha}`\n"
                f"- **Date:** {self.run_date}\n\n"
                f"The workflow failed but no individual test or step failure "
                f"could be identified.\n"
                f"Please investigate the run logs directly."
            )
            comment_on_issue(self.repo, existing, comment)
            url = get_issue_url(self.repo, existing)
            self.slack_lines.append(
                f":question: Could not identify specific failures (<{url}|#{existing}>)"
            )
        else:
            body = (
                f"## CI failures — could not identify specific failing test(s) or step(s)\n\n"
                f"- **Run:** {self.run_url}\n"
                f"- **Commit:** `{self.short_sha}`\n"
                f"- **Date:** {self.run_date}\n\n"
                f"The workflow failed but no individual test or step failure "
                f"could be identified.\n"
                f"Please investigate the run logs directly.\n\n"
                f"---\n"
                f"*This issue was automatically created by the flaky test tracker workflow.*\n"
                f"*Subsequent unparseable failures will be added as comments below.*"
            )
            url = create_issue(
                self.repo, issue_title, ["ci-failure", "autogenerated"], body
            )
            self.slack_lines.append(
                f":question: Could not identify specific failures (<{url}|issue>)"
            )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--run-url", required=True)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--commit-sha", required=True)
    parser.add_argument("--output-file", required=True)
    args = parser.parse_args()

    failing_tests = read_lines(f"{args.input_dir}/failing_tests.txt")
    failed_steps = read_lines(f"{args.input_dir}/failed_steps.txt")

    tracker = IssueTracker(args.repo, args.run_id, args.run_url, args.commit_sha)

    # Process failing tests
    if failing_tests:
        if len(failing_tests) > GROUPING_THRESHOLD:
            print(f"Too many test failures ({len(failing_tests)}) - creating a single grouped issue")
            tracker.create_grouped_issue("test", failing_tests)
        else:
            for test_name in failing_tests:
                print(f"Processing test: {test_name}")
                body = tracker.test_issue_body(test_name)
                tracker.track_item(test_name, "Flaky test", "flaky-test", body)

    # Process failed steps
    if failed_steps:
        if len(failed_steps) > GROUPING_THRESHOLD:
            print(f"Too many step failures ({len(failed_steps)}) - creating a single grouped issue")
            tracker.create_grouped_issue("step", failed_steps)
        else:
            for step_entry in failed_steps:
                print(f"Processing step: {step_entry}")
                body = tracker.step_issue_body(step_entry)
                tracker.track_item(step_entry, "Flaky step", "flaky-step", body)

    # Fallback for unparseable failures
    if not failing_tests and not failed_steps:
        tracker.handle_unparseable()

    # Write output
    summary = "\n".join(tracker.slack_lines) if tracker.slack_lines else (
        ":question: Could not identify specific failures"
    )
    with open(args.output_file, "w") as f:
        f.write(summary + "\n")

    print(f"Slack summary written to {args.output_file}")


if __name__ == "__main__":
    main()
