# For testing purposes when no value is set to any
# local storages (including simulated must be enabled)
export ARCTICDB_LOCAL_STORAGE_TESTS_ENABLED=1
export ARCTICDB_STORAGE_LMDB=
export ARCTICDB_STORAGE_AZURITE=
export ARCTICDB_STORAGE_MONGO=
export ARCTICDB_STORAGE_MEM=
export ARCTICDB_STORAGE_NFS=
export ARCTICDB_STORAGE_SIM_S3=
export ARCTICDB_STORAGE_SIM_GCP=

export ARCTICDB_TEST_ENCODING_V1=
export ARCTICDB_TEST_ENCODING_V2=

export ARCTICDB_PERSISTENT_STORAGE_TESTS=
export ARCTICDB_STORAGE_AWS_S3=
export ARCTICDB_STORAGE_GCP=
export ARCTICDB_STORAGE_AZURE=
