name: Bug Report
description: Create a report to help us reproduce and correct the bug
labels: ['bug']

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already
      addressed by searching through [the past issues](https://github.com/man-group/ArcticDB/issues).

- type: textarea
  attributes:
    label: Describe the bug
    description: >
      A clear and concise description of what the bug is.

- type: textarea
  attributes:
    label: Steps/Code to Reproduce
    description: |
      Please add a [minimal code example](https://matthewrocklin.com/minimal-bug-reports) that can reproduce the error
      and the output/exception/stack trace if possible.

      Be as succinct as possible and avoid external data files. Instead you can generate synthetic data using `numpy.random`.
      If your bug report appears to be dependent on external data files and cannot be reproduced without them, please describe your data
      files in as much detail as you can.

      If the code is too long, feel free to put it in a [public gist](https://gist.github.com) and link it in the issue.

      We acknowledge that this requires some effort but it really helps us locate the problem and we thank you for helping us out ❤️
    placeholder: |
      ```python
      from arcticdb import Arctic

      Arctic()
      ```

      Output:
      ```python-traceback
      ---------------------------------------------------------------------------
      TypeError                                 Traceback (most recent call last)
      Cell In[4], line 1
      ----> 1 Arctic()
      TypeError: Arctic.__init__() missing 1 required positional argument: 'uri'
      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Results
    placeholder: >
      Example: No error is thrown.
  validations:
    required: true

- type: textarea
  attributes:
    label: OS, Python Version and ArcticDB Version
    description: |
      Run this command and paste the result bellow:
        ```bash
        python3 -c "import sys; print('Python:', sys.version); import platform; print('OS:', platform.platform()); import arcticdb; print('ArcticDB:', arcticdb.__version__);"
        ```
    placeholder: >
      Python: 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
      OS: Linux-6.2.15-300.fc38.x86_64-x86_64-with-glibc2.37
      ArcticDB: 1.1.0
  validations:
    required: true

- type: input
  attributes:
    label: Backend storage used
    placeholder: >
      AWS S3, GCP S3, LMDB, etc.

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context about the problem here.

- type: markdown
  attributes:
    value: >
      Thank you for contributing to ArcticDB!
