FROM quay.io/pypa/manylinux_2_28_x86_64

RUN dnf update -y
RUN dnf remove -y 'gcc-toolset-*'
# Looks like clang depends on the gcc-toolset-14, so try to install the libatomic-devel from there
RUN dnf install -y zip flex bison clang llvm lldb gcc-toolset-14-libatomic-devel krb5-devel cyrus-sasl-devel openssl-devel \
unzip tar epel-release jq wget libcurl-devel git-lfs cmake3 \
python3.11-devel python3.11-pip perl-IPC-Cmd lld compiler-rt

RUN clang++ -fuse-ld=lld -Wl,--version || echo "LLD installation verification failed"
RUN ldconfig

RUN dnf groupinstall -y 'Development Tools'
RUN dnf install -y mono-complete

RUN dnf clean all

RUN wget -nv https://github.com/mozilla/sccache/releases/download/v0.8.2/sccache-v0.8.2-x86_64-unknown-linux-musl.tar.gz
RUN tar xvf sccache*.tar.gz
RUN mv sccache-*/sccache .
RUN chmod 555 sccache

RUN cp sccache /usr/local/bin/

ENV CC=/usr/bin/clang
ENV CMAKE_C_COMPILER=/usr/bin/clang
ENV CXX=/usr/bin/clang++
ENV CMAKE_CXX_COMPILER=/usr/bin/clang++
ENV LD_LIBRARY_PATH=/usr/lib64:/usr/lib
ENV PATH=/opt/python/cp311-cp311/bin:/usr/bin:${PATH}
