from typing import Optional

_cleanup: PyCapsule

def get_config_double(arg0: str) -> Optional[float]: ...
def get_config_int(arg0: str) -> Optional[int]: ...
def get_config_string(arg0: str) -> Optional[str]: ...
def get_version_string() -> str: ...
def read_runtime_config(arg0: object) -> None: ...
def set_config_double(arg0: str, arg1: float) -> None: ...
def set_config_int(arg0: str, arg1: int) -> None: ...
def set_config_string(arg0: str, arg1: str) -> None: ...
def unset_config_double(arg0: str) -> None: ...
def unset_config_int(arg0: str) -> None: ...
def unset_config_string(arg0: str) -> None: ...
