from typing import Any

class Column:
    def __init__(self) -> None: ...
    @property
    def row_count(self) -> int: ...

class ColumnData:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def type(self) -> Any: ...

class StringPool:
    def __init__(self) -> None: ...
    def as_buffer_info(self) -> buffer_info: ...
    @property
    def nbytes(self) -> int: ...
