name: 'Install wheel'
description: 'Install the wheel and dependencies'
inputs:
  python_impl_name:
    description: 'The python version tag eg cp36'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cmake -P cpp/CMake/CpuCount.cmake | sed 's/^-- //' | tee -a $GITHUB_ENV
        python -V
        cd "$RUNNER_TEMP" # Works for Windows-style paths as well
        python -m pip install --force-reinstall *${{inputs.python_impl_name}}*.whl
        python -m pip install arcticdb[Testing] pytest-split
        python -m pip uninstall -y pytest-cpp || true # No longer works on 3.6
        if [[ -n "$MSYSTEM" ]] ; then
          echo "LOCALAPPDATA=$LOCALAPPDATA" | tee -a $GITHUB_ENV
          MSYS_NO_PATHCONV=1 reg.exe ADD 'HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps'
          cd "/proc/registry/HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft"
          find "Windows NT/CurrentVersion/AeDebug" "Windows/Windows Error Reporting/LocalDumps" \
            -type f -print -exec xxd -c 64 '{}' \; || true
        fi
      shell: bash
