#include <arcticdb/arrow/arrow_c_data_interface.hpp>

enum ArrowType {
    ARROW_TYPE_UNINITIALIZED = 0,
    ARROW_TYPE_NA = 1,
    ARROW_TYPE_BOOL,
    ARROW_TYPE_UINT8,
    ARROW_TYPE_INT8,
    ARROW_TYPE_UINT16,
    ARROW_TYPE_INT16,
    ARROW_TYPE_UINT32,
    ARROW_TYPE_INT32,
    ARROW_TYPE_UINT64,
    ARROW_TYPE_INT64,
    ARROW_TYPE_HALF_FLOAT,
    ARROW_TYPE_FLOAT,
    ARROW_TYPE_DOUBLE,
    ARROW_TYPE_STRING,
    ARROW_TYPE_BINARY,
    ARROW_TYPE_FIXED_SIZE_BINARY,
    ARROW_TYPE_DATE32,
    ARROW_TYPE_DATE64,
    ARROW_TYPE_TIMESTAMP,
    ARROW_TYPE_TIME32,
    ARROW_TYPE_TIME64,
    ARROW_TYPE_INTERVAL_MONTHS,
    ARROW_TYPE_INTERVAL_DAY_TIME,
    ARROW_TYPE_DECIMAL128,
    ARROW_TYPE_DECIMAL256,
    ARROW_TYPE_LIST,
    ARROW_TYPE_STRUCT,
    ARROW_TYPE_SPARSE_UNION,
    ARROW_TYPE_DENSE_UNION,
    ARROW_TYPE_DICTIONARY,
    ARROW_TYPE_MAP,
    ARROW_TYPE_EXTENSION,
    ARROW_TYPE_FIXED_SIZE_LIST,
    ARROW_TYPE_DURATION,
    ARROW_TYPE_LARGE_STRING,
    ARROW_TYPE_LARGE_BINARY,
    ARROW_TYPE_LARGE_LIST,
    ARROW_TYPE_INTERVAL_MONTH_DAY_NANO
};

namespace arrow_cpp {

    class Buffer {
        size_t bytes() const;


    };

    class Array {

    };

    class RecordBatch {

    };

    class Table {

    };


}
