name: Install Azurite with Retry
description: Installs Azurite globally with retry logic
inputs:
  max_retries:
    description: Number of retry attempts
    required: false
    default: "3"

runs:
  using: "composite"
  steps:
    - name: Retry Azurite Installation
      shell: bash -l {0}  
      run: |
        MAX_RETRIES=${{ inputs.max_retries }}
        COUNT=0

        until npm install -g azurite; do
          COUNT=$((COUNT+1))
          echo "Attempt $COUNT failed. Retrying..."
          if [ $COUNT -ge $MAX_RETRIES ]; then
            echo "Installation failed after $MAX_RETRIES attempts."
            exit 1
          fi
          sleep 2
        done

        echo "Azurite installed successfully!"
