from typing import Any, Optional, Tuple
from arcticdb.version_store._normalization import normalize_metadata
from arcticdb.exceptions import ArcticNativeException, ArcticDbNotYetImplemented
from arcticdb.log import version as log

from typing import Any, Optional, Tuple
from arcticdb.version_store._store import VersionedItem
from arcticdb.exceptions import ArcticNativeException, ArcticDbNotYetImplemented
from arcticdb.log import version as log

from arcticdb_ext.version_store import read_dataframe_from_file, write_dataframe_to_file

# Import our normalization functions and normalizer class.
from arcticdb.version_store._normalization import CompositeNormalizer, normalize_metadata

def try_normalize_stateless(
        dataframe: Any,
        metadata: Any = None,
        *,
        pickle_on_failure: bool = False,
        dynamic_strings: bool = True,
        coerce_columns: Optional[Any] = None,
        dynamic_schema: bool = False,
        empty_types: bool = False,
        normalizer: Any,
        norm_failure_options_msg: str = "",
        **kwargs,
) -> Tuple[Any, Any, Any]:
    """
    Stateless normalization without custom normalization.

    Parameters
    ----------
    dataframe : Any
        Data to be normalized (e.g. a pandas DataFrame, Series or numpy array).
    metadata : Any, optional
        User‐defined metadata. If provided, it is normalized via normalize_metadata().
    pickle_on_failure : bool, optional
        Whether to fallback to pickled normalization (if supported) on failure.
    dynamic_strings : bool, optional
        Whether to use dynamic strings.
    coerce_columns : Optional[Any], optional
        Coercion mapping for columns.
    dynamic_schema : bool, optional
        Whether to treat the schema as dynamic.
    empty_types : bool, optional
        If True, an empty DataFrame/Series is treated specially.
    normalizer : Any
        A normalizer instance (for example, a DataFrameNormalizer or CompositeNormalizer)
        that exposes a normalize(dataframe, …) method.
    norm_failure_options_msg : str, optional
        Extra information appended to error messages.
    kwargs :
        Additional keyword arguments passed to the normalizer.normalize method.

    Returns
    -------
    Tuple[Any, Any, Any]
        A triple (udm, item, norm_meta) where:
          • udm is the normalized user metadata (as returned by normalize_metadata),
          • item is the normalized native object (for example, an NPDDataFrame tuple), and
          • norm_meta is the normalization metadata.

    Raises
    ------
    ArcticNativeException or ArcticDbNotYetImplemented if normalization fails.
    """
    # Normalize the user metadata
    udm = normalize_metadata(metadata)

    try:
        # Call the normalizer's normalize method with the given options.
        item, norm_meta = normalizer.normalize(
            dataframe,
            pickle_on_failure=pickle_on_failure,
            dynamic_strings=dynamic_strings,
            coerce_columns=coerce_columns,
            dynamic_schema=dynamic_schema,
            empty_types=empty_types,
            **kwargs,
        )
    except ArcticDbNotYetImplemented as ex:
        log.debug(f"ArcticDbNotYetImplemented: data: {dataframe}, metadata: {metadata}")
        raise ArcticDbNotYetImplemented(f"Not supported during normalization: {ex}, {norm_failure_options_msg}")
    except Exception as ex:
        log.debug(f"ArcticNativeException: data: {dataframe}, metadata: {metadata}")
        raise ArcticNativeException(f"Error while normalizing: {ex}")

    if norm_meta is None:
        raise ArcticNativeException("Normalization returned a null metadata result")

    return udm, item, norm_meta

def denormalize_stateless(item: Any, norm_meta: Any, normalizer: Any) -> Any:
    """
    Stateless denormalization.

    Parameters
    ----------
    item : Any
        The native representation (for example, a FrameData instance) generated by normalization.
    norm_meta : Any
        The associated normalization metadata.
    normalizer : Any
        A normalizer instance exposing a denormalize(item, norm_meta) method.

    Returns
    -------
    Any
        The denormalized Python object (such as a pandas DataFrame).

    Raises
    ------
    ArcticNativeException if denormalization fails.
    """
    try:
        return normalizer.denormalize(item, norm_meta)
    except Exception as ex:
        raise ArcticNativeException(f"Error while denormalizing: {ex}")

def to_file(symbol: str, data: Any, file_path: str, metadata: Optional[Any] = None, **kwargs) -> VersionedItem:
    """
    Write `data` (a DataFrame, Series or ndarray) to a file using the new C++ method.

    The function uses a stateless normalization function to convert the data
    into Arctic's native representation before writing, and calls the C++ binding:

         write_dataframe_to_file(stream_id, path, item, norm, user_meta)

    Parameters:
      symbol    : String identifier used as the stream_id.
      data      : The data to be written.
      file_path : Path to a file where the data is stored.
      metadata  : Optional metadata associated with the data.
      kwargs    : Additional options for normalization (e.g. pickle_on_failure, dynamic_strings).

    Returns a VersionedItem representing the written symbol. (Since
    the C++ function returns void, this example returns a VersionedItem with minimal fields.)
    """
    # Get a "default" composite normalizer instance.
    normalizer = CompositeNormalizer()
    # Normalize without custom normalization.
    udm, item, norm_meta = try_normalize_stateless(
        dataframe=data,
        metadata=metadata,
        pickle_on_failure=kwargs.get("pickle_on_failure", False),
        dynamic_strings=kwargs.get("dynamic_strings", True),
        coerce_columns=kwargs.get("coerce_columns"),
        dynamic_schema=kwargs.get("dynamic_schema", False),
        empty_types=kwargs.get("empty_types", False),
        normalizer=normalizer,
        norm_failure_options_msg="Error in to_file normalization",
        **kwargs,
    )
    # Call the C++ file writing method.
    write_dataframe_to_file(symbol, file_path, item, norm_meta, udm)
    # Return a dummy VersionedItem.
    return VersionedItem(
        symbol=symbol,
        library=file_path,
        data=None,
        version=0,
        metadata=metadata,
        host="file",
        timestamp=0,
    )

# File reading method
def from_file(symbol: str, file_path: str, read_query: Optional[Any] = None, read_options: Optional[Any] = None, **kwargs) -> VersionedItem:
    """
    Read a dataframe from a file using the new C++ method.

    The C++ binding is:

         read_dataframe_from_file(stream_id, path, read_query, read_options)

    The resulting native object is denormalized using the stateless denormalization function.

    Parameters:
      symbol      : The stream identifier.
      file_path   : Path to the file from which to read.
      read_query  : An optional read query object (if needed).
      read_options: Optional read options; if not provided, defaults will be used.
      kwargs      : Additional keyword parameters (unused here).

    Returns a VersionedItem whose data attribute is filled with the denormalized Python object.
    """
    # Set up default read options if missing.
    if read_options is None:
        from arcticdb_ext.version_store import PythonVersionStoreReadOptions
        read_options = PythonVersionStoreReadOptions()

    if read_query is None:
        from arcticdb_ext.version_store import PythonVersionStoreReadQuery
        read_query = PythonVersionStoreReadQuery()

    # Call the C++ file read method.
    read_result = read_dataframe_from_file(symbol, file_path, read_query, read_options)
    # Instantiate the same normalizer for denormalization.
    normalizer = CompositeNormalizer()
    # Convert the native frame to a Python object.
    data = denormalize_stateless(read_result.frame_and_descriptor, read_result.norm, normalizer)
    return VersionedItem(
        symbol=symbol,
        library=file_path,
        data=data,
        version=read_result.version,
        metadata=None,  # If needed, further processing of udm can be added.
        host="file",
        timestamp=read_result.timestamp,
    )