if(NOT DEFINED ENV{CMAKE_BUILD_PARALLEL_LEVEL} OR "$ENV{CMAKE_BUILD_PARALLEL_LEVEL}" STREQUAL "")
    include(ProcessorCount)
    ProcessorCount(_proc_count)
    if(${_proc_count} LESS 2)
        message(WARNING "Failed to determine the available processor count. Assuming you have at least 2 cores. \
            Please set the CMAKE_BUILD_PARALLEL_LEVEL environment variable.")
        set(ENV{CMAKE_BUILD_PARALLEL_LEVEL} 2)
    else()
        cmake_host_system_information(RESULT _physical_mb QUERY TOTAL_PHYSICAL_MEMORY)
        # C++ compiler processes can use up to 3GB each; cap parallelism to avoid OOM
        math(EXPR _mem_jobs "${_physical_mb} / 3000")
        if(${_mem_jobs} LESS 1)
            set(_mem_jobs 1)
        endif()
        if(${_proc_count} LESS ${_mem_jobs})
            set(_jobs ${_proc_count})
        else()
            set(_jobs ${_mem_jobs})
        endif()
        if(${_jobs} LESS ${_proc_count})
            message(NOTICE "Limiting parallel build to ${_jobs} jobs (RAM: ${_physical_mb}MB, cores: ${_proc_count}). \
                Set CMAKE_BUILD_PARALLEL_LEVEL to override.")
        endif()
        set(ENV{CMAKE_BUILD_PARALLEL_LEVEL} ${_jobs})
    endif()
endif()
message(STATUS "CMAKE_BUILD_PARALLEL_LEVEL=$ENV{CMAKE_BUILD_PARALLEL_LEVEL}")
