name: Build with conda

permissions:
  contents: read

run-name: Building ${{github.ref_name}} on ${{github.event_name}} by ${{github.actor}}

concurrency:
  group: ${{github.ref}}-${{github.workflow}}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      run_cpp_tests:             {required: true,  type: boolean, default: true,  description: Run C++ tests}
      persistent_storage:        {required: false, type: choice,  default: 'no',  description: Persistent storage type, options: ['no', 'AWS_S3', 'GCPXML', 'AZURE']}
      debug_enabled:             {required: false, type: boolean, default: false, description: Run the build with debugging enabled}
      run_enable_logging:        {required: false, type: boolean, default: false, description: Enable debug logging}
      run_commandline:           {required: false, type: string,  default: '',    description: Run custom commandline before tests}
      run_custom_pytest_command: {required: false, type: string,  default: '',    description: Run custom pytest command or additional arguments}

jobs:
  linux_64:
    uses: ./.github/workflows/compile_and_test_with_conda_unix.yml
    secrets: inherit
    with:
      runner:                    ubuntu-22.04
      platform:                  linux_64
      preset:                    linux-conda-release
      cache_key:                 conda-env-linux_64
      free_disk_space:           true
      install_mongodb:           true
      hypothesis_profile:        ci_linux
      run_cpp_tests:             ${{inputs.run_cpp_tests}}
      cpp_tests_enabled:         true
      persistent_storage:        ${{inputs.persistent_storage || 'no'}}
      debug_enabled:             ${{inputs.debug_enabled || false}}
      run_enable_logging:        ${{inputs.run_enable_logging || false}}
      run_commandline:           ${{inputs.run_commandline || ''}}
      run_custom_pytest_command: ${{inputs.run_custom_pytest_command || ''}}

  linux_aarch64:
    uses: ./.github/workflows/compile_and_test_with_conda_unix.yml
    secrets: inherit
    with:
      runner:                    ubuntu-22.04-arm
      platform:                  linux_aarch64
      preset:                    linux-conda-release
      cache_key:                 conda-env-linux_aarch64
      free_disk_space:           true
      install_mongodb:           true
      run_cpp_tests:             ${{inputs.run_cpp_tests}}
      cpp_tests_enabled:         true
      persistent_storage:        ${{inputs.persistent_storage || 'no'}}
      debug_enabled:             ${{inputs.debug_enabled || false}}
      run_enable_logging:        ${{inputs.run_enable_logging || false}}
      run_commandline:           ${{inputs.run_commandline || ''}}
      run_custom_pytest_command: ${{inputs.run_custom_pytest_command || ''}}

  osx_arm64:
    uses: ./.github/workflows/compile_and_test_with_conda_unix.yml
    secrets: inherit
    with:
      runner:                    macos-14
      platform:                  osx_arm64
      preset:                    macos-conda-release
      cache_key:                 conda-env-osx_arm64
      hypothesis_profile:        ci_macos
      run_cpp_tests:             ${{inputs.run_cpp_tests}}
      cpp_tests_enabled:         true
      persistent_storage:        ${{inputs.persistent_storage || 'no'}}
      debug_enabled:             ${{inputs.debug_enabled || false}}
      run_enable_logging:        ${{inputs.run_enable_logging || false}}
      run_commandline:           ${{inputs.run_commandline || ''}}
      run_custom_pytest_command: ${{inputs.run_custom_pytest_command || ''}}

  win_64:
    uses: ./.github/workflows/compile_and_test_with_conda_win.yml
    secrets: inherit
    with:
      runner:                    windows-latest
      platform:                  win_64
      preset:                    windows-cl-conda-release
      cache_key:                 conda-env-win_64
      run_cpp_tests:             ${{inputs.run_cpp_tests}}
      persistent_storage:        ${{inputs.persistent_storage || 'no'}}
      debug_enabled:             ${{inputs.debug_enabled || false}}
      run_enable_logging:        ${{inputs.run_enable_logging || false}}
      run_commandline:           ${{inputs.run_commandline || ''}}
      run_custom_pytest_command: ${{inputs.run_custom_pytest_command || ''}}

  can_merge_conda:
    name: All conda jobs completed
    needs: [linux_64, linux_aarch64, osx_arm64, win_64]
    if: |
      always() &&
      !failure() &&
      !cancelled()
    runs-on: ubuntu-22.04
    steps:
      - run: echo All conda jobs completed!