name: Docs Build
on:
  workflow_dispatch:
    inputs:
      version: { type: string, required: false, description: The version to build docs for, used as git tag and pypi version.  If not specified then use master and wheel from the last successful build.}
      latest: { type: boolean, required: false, description: Alias this version as the 'latest' stable docs.}
      deploy: { type: boolean, required: false, description: Push the built docs to the docs-pages branch on github.}
      
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        ref: ${{inputs.version || 'master'}}

      - name: Detect runner Python implementation
        if: ${{!inputs.version}}
        run: |
          python3 -c 'import platform
          prefix = {"CPython": "cp", "PyPy": "pp"}[platform.python_implementation()]
          v = platform.python_version_tuple()
          print(f"PY_IMPL={prefix}{v[0]}{v[1]}")' | tee -a $GITHUB_ENV
  
      - id: download-wheel-artifact
        name: Download wheel artifact from last successful build
        if: ${{!inputs.version}}
        uses: dawidd6/action-download-artifact@v2
        with:
          name: wheel-${{env.PY_IMPL}}-manylinux_x86_64
          workflow: build.yml
          workflow_conclusion: success
          branch: master

      - name: Install documenation dependencies (including ArcticDB)
        run: |
          pip3 install mkdocs-material mkdocs-jupyter mkdocstrings[python] black pybind11-stubgen ${{inputs.version && join('arcticdb==',inputs.version) || 'arcticdb-*.whl'}}

      - name: Stubfile generation for arcticdb_ext
        # stubfiles will be generated into docs/mkdocs/arcticdb_ext and so imported as arcticdb_ext by mkdocs when it builds
        # FIXME --ignore-all-errors may mask new errors and should be removed when we are compliant
        run: |  
          cd docs/mkdocs
          pybind11-stubgen arcticdb_ext.version_store --ignore-all-errors -o .

      - name: List docs versions deployed to docs-pages branch
        run: |
          cd docs/mkdocs
          mike list

      - name: Versioned mkDocs build 
        run: |
          cd docs/mkdocs
          mike set-default latest
          mike deploy ${{inputs.deploy && '--push'}} ${{inputs.version || 'dev'}} ${{inputs.latest && 'latest'}} --message "Deploying docs for ${{inputs.version || 'dev'}} ${{inputs.latest && 'latest'}}"
