name: Run Installation Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install arcticdb and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install arcticdb
        pip download arcticdb --only-binary=:all: -d .
        pip install --force-reinstall $(ls arcticdb*.whl)[Testing] pytest-split

    - name: Set persistent storage variables
      if: always()
      uses: ./.github/actions/set_persistent_storage_env_vars
      with:
        aws_access_key: "${{ secrets.AWS_S3_ACCESS_KEY }}"
        aws_secret_key: "${{ secrets.AWS_S3_SECRET_KEY }}"
        gcp_access_key: "${{ secrets.GCP_S3_ACCESS_KEY }}"
        gcp_secret_key: "${{ secrets.GCP_S3_SECRET_KEY }}"
        persistent_storage: "${{ inputs.persistent_storage }}"
        strategy_branch: "${{ env.distinguishing_name }}"        

    - name: Build protobuf
      run: |
        python setup.py protoc --build-lib python        

    - name: Run tests
      run: |
        pytest -s -m installation --log-file="tests.log" 

    - name: Upload the logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-log
        path: |
          ./*test*        