name: Run Installation Tests v3

on:
  push:
    branches: 
      - installation_tests
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System to test'
        required: false
        default: 'ubuntu-22.04'
        type: choice
        options:
          - all
          - ubuntu-22.04
          - windows-latest
          - macos-latest
      python:
        description: 'Python Version to test'
        required: false
        default: '3.13'
        type: choice
        options:
          - all
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
jobs:

  test:
    runs-on: ${{ inputs.os != 'all' && inputs.os || matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-22.04, windows-latest, macos-latest]
        #python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        #os: [ubuntu-22.04, windows-latest, macos-13]
        #python: ["3.8", "3.12"]
        include:
          - os: ubuntu-22.04
            python: "3.7"
          - os: windows-latest
            python: "3.8"
          - os: macos-latest
            python: "3.9"
          - os: windows-latest
            python: "3.10"
          - os: macos-latest
            python: "3.11"
          - os: ubuntu-22.04
            python: "3.12"
          - os: ubuntu-22.04
            python: "3.13"
      fail-fast: false  

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python || inputs.python}}

    - name: Delete python/arcticdb folder
      shell: bash -l {0}
      run: |
        rm -rf python/arcticdb

    - name: Install arcticdb and dependencies
      if: ${{ !(contains(matrix.os, 'macos') || contains(inputs.os, 'macos'))}}
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install arcticdb
        pip install wheel
        pip install setuptools
        pip install pytest

    # Install conda environment
    - name: Install Conda environment from environment_unix.yml
      uses: mamba-org/setup-micromamba@v2.0.0
      if: ${{ contains(matrix.os, 'macos') || contains(inputs.os, 'macos')}}
      with:
        environment-file: installation_tests/python/environment_unix.yml
        environment-name: arcticdb
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Set persistent storage variables
      if: always()
      uses: ./.github/actions/set_persistent_storage_env_vars
      with:
        aws_access_key: "${{ secrets.AWS_S3_ACCESS_KEY }}"
        aws_secret_key: "${{ secrets.AWS_S3_SECRET_KEY }}"
        gcp_access_key: "${{ secrets.GCP_S3_ACCESS_KEY }}"
        gcp_secret_key: "${{ secrets.GCP_S3_SECRET_KEY }}"
        persistent_storage: "true"

    - name: Build protobuf
      shell: bash -l {0}      
      run: |
        python setup.py protoc --build-lib python        

    - name: Set environment variables 
      shell: bash -l {0}      
      run: |
        echo "ARCTICDB_STORAGE_GCP=1" >> $GITHUB_ENV        
        echo "ARCTICDB_STORAGE_AWS_S3=1" >> $GITHUB_ENV        
        echo "ARCTICDB_PERSISTENT_STORAGE_TESTS=1" >> $GITHUB_ENV

    - name: Run tests
      shell: bash -l {0}      
      run: |
        echo $pwd
        #export ARCTICDB_STORAGE_GCP=1
        #export ARCTICDB_STORAGE_AWS_S3=1
        cd python
        pytest -s -rs --log-file="tests.log" -v -m installation


    - name: Upload the logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ matrix.os || inputs.os }}-${{ matrix.python || inputs.python}}
        path: |
          ./*test*        

