name: __real_storage_seed
on:
  workflow_call:
    inputs:
      matrix:            {required: true, type: string, description: JSON string to feed into the matrix}
      python_deps_ids:   {default: '[""]', type: string, description: Follower test matrix parameter. JSON string.}
      python3:           {default: -1, type: number, description: Python 3 minor version}
      clear:             {default: 0, type: number, description: Controls wheather we will clear the libraries in the versions stores that we test against}      
      # TODO: Maybe we should add these as GitHub variables
      bucket:            {default: 'arcticdb-ci-test-bucket-01', type: string, description: The name of the S3 bucket that we will test against}
      endpoint:          {default: 's3.eu-west-2.amazonaws.com', type: string, description: The address of the S3 endpoint}
      region:            {default: 'eu-west-2', type: string, description: The S3 region of the bucket}
jobs:
  seed_storage:
    strategy:
      matrix:
        # Declaring the dummy fields here to aid the Github Actions linting in VSCode and to provide documentation
        os: [0] # Decouples the steps from any distro version changes
        distro: [0]
        cmake_preset_prefix: [0]
        cibw_build_suffix: [0]
        envs: [0]
        build_dir: [0] # Must be an absolute path
        symbols: [0] # Glob for symbol symbol files. Used for including in follower builds and exclusion on others.
        do_not_archive: [0]
        test_services: [0] # Github service containers to spin up for the pytest run
        exclude:
            - os: 0
        include:
            - ${{fromJSON(inputs.matrix)[0]}} # The items after 0 are for tests only
    runs-on: ${{matrix.distro}}
    defaults:
      run: {shell: bash}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Python (Linux)
        if: matrix.os == 'linux'
        run: echo /opt/python/${{env.python_impl_name}}*/bin >> $GITHUB_PATH

      - name: Select Python (Windows)
        if: matrix.os == 'windows'
        uses: actions/setup-python@v4
        with:
          python-version: "3.${{inputs.python3}}"

      - name: Install latest release
        run: |
          pip install arcticdb
          pip install pandas < 2

      - name: Set real storage variables
        run: |
          echo "ARCTICDB_REAL_STORAGE_TESTS=1" >> $GITHUB_ENV
          echo "ARCTICDB_REAL_S3_BUCKET=${{ inputs.bucket }}" >> $GITHUB_ENV
          echo "ARCTICDB_REAL_S3_ENDPOINT=${{ inputs.endpoint }}" >> $GITHUB_ENV
          echo "ARCTICDB_REAL_S3_REGION=${{ inputs.region }}" >> $GITHUB_ENV
          echo "ARCTICDB_REAL_S3_CLEAR=${{ inputs.clear }}" >> $GITHUB_ENV
          echo "ARCTICDB_REAL_S3_ACCESS_KEY=${{ secrets.AWS_S3_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "ARCTICDB_REAL_S3_SECRET_KEY=${{ secrets.AWS_S3_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Seed the storage
        run: |
          echo "Running seed for ${{inputs.matrix.os}}_3.${{inputs.python3}}"
          python build_tooling/seed_storage.py "${{inputs.matrix.os}}_3.${{inputs.python3}}"
          
