name: Run specific tests on matrix
on:
  workflow_call:
    inputs:
      os: {required: true, type: string}
      test_suite: {required: true, type: string}

jobs:
  run_tests:
    strategy:
      fail-fast: false
    name: Run tests on python 3.11 and ${{ inputs.os }} with ${{ inputs.test_suite }} test suite
    runs-on: ${{ inputs.os == 'linux' && 'ubuntu-latest' || 'windows-latest' }}
    container: ${{ inputs.os == 'linux' && 'ghcr.io/man-group/arcticdb-dev:latest' || null }}
    defaults:
      run: {shell: bash}
    env:
      VCPKG_NUGET_USER: ${{secrets.VCPKG_NUGET_USER || github.repository_owner}}
      VCPKG_NUGET_TOKEN: ${{secrets.VCPKG_NUGET_TOKEN || secrets.GITHUB_TOKEN}}
      VCPKG_MAN_NUGET_USER: ${{secrets.VCPKG_MAN_NUGET_USER}} # For forks to download pre-compiled dependencies from the Man repo
      VCPKG_MAN_NUGET_TOKEN: ${{secrets.VCPKG_MAN_NUGET_TOKEN}}
      ARCTICDB_BUILD_DIR: ${{ inputs.os == 'windows' && 'C:/cpp_build' || '/tmp/cpp_build' }}
      ARCTICDB_VCPKG_PACKAGES_DIR: ${{ inputs.os == 'windows' && 'C:/vcpkg_packages' || '' }}
    steps:  
      - uses: actions/checkout@v3.3.0
        with:
          lfs: 'true'
          submodules: recursive
          token: ${{ secrets.ARCTICDB_TEST_PAT }}

      - name: Extra envs
        shell: bash -l {0}
        run: |
          . build_tooling/vcpkg_caching.sh # Linux follower needs another call in CIBW
          echo -e "VCPKG_BINARY_SOURCES=$VCPKG_BINARY_SOURCES
          VCPKG_ROOT=$PLATFORM_VCPKG_ROOT" | tee -a $GITHUB_ENV
          cmake -P cpp/CMake/CpuCount.cmake | sed 's/^-- //' | tee -a $GITHUB_ENV
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: ${{vars.CMAKE_BUILD_PARALLEL_LEVEL}}

      - name: Find and remove ccache # See PR: #945
        if: inputs.os == 'windows'
        run: rm $(which ccache) || true
  
      - name: Prepare C++ compilation env
        run: . build_tooling/prep_cpp_build.sh # Also applies to Windows

        # When a GitHub Windows image gets update the MSVC compiler also can get updated. New compilers can have compilation errors in Arctic or in the VCPKG dependencies.
        # We needd to pin a particular MSVC so that runner updates don't affect us.
        # When the MSVC version is update custom-triplets/x64-windows-static-msvc.cmake must also be updated with the correct toolsed version.
      - name: Install Required MSVC
        if: inputs.os == 'windows'
        run: |
          choco install -y -f visualstudio2022buildtools --version=117.11.4 --params "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --installChannelUri https://aka.ms/vs/17/release/390666095_1317821361/channel"
          choco install -y ninja

      - name: Install local dependencies with pip
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -ve .[Testing]

      - name: Run tests
        run: |
          cd python
          pytest --timeout=3600 -n auto -v ${{ inputs.test_suite }}